# --- !Ups

# create table "user" ("userID" VARCHAR NOT NULL PRIMARY KEY,"firstName" VARCHAR,"lastName" VARCHAR,"fullName" VARCHAR,"email" VARCHAR,"avatarURL" VARCHAR);
# create table "logininfo" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"providerID" VARCHAR NOT NULL,"providerKey" VARCHAR NOT NULL);
# create table "userlogininfo" ("userID" VARCHAR NOT NULL,"loginInfoId" BIGINT NOT NULL);
# create table "passwordinfo" ("hasher" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"salt" VARCHAR,"loginInfoId" BIGINT NOT NULL);
# create table "oauth1info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"token" VARCHAR NOT NULL,"secret" VARCHAR NOT NULL,"loginInfoId" BIGINT NOT NULL);
# create table "oauth2info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"accesstoken" VARCHAR NOT NULL,"tokentype" VARCHAR,"expiresin" INTEGER,"refreshtoken" VARCHAR,"logininfoid" BIGINT NOT NULL);
# create table "openidinfo" ("id" VARCHAR NOT NULL PRIMARY KEY,"logininfoid" BIGINT NOT NULL);
# create table "openidattributes" ("id" VARCHAR NOT NULL,"key" VARCHAR NOT NULL,"value" VARCHAR NOT NULL);

create table `user` (`userID` VARCHAR(255) NOT NULL PRIMARY KEY,`firstName` VARCHAR(255),`lastName` VARCHAR(255),`fullName` VARCHAR(255),`email` VARCHAR(255),`avatarURL` VARCHAR(255));
create table `logininfo` (`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`providerID` VARCHAR(255) NOT NULL,`providerKey` VARCHAR(255) NOT NULL);
create table `userlogininfo` (`userID` VARCHAR(255) NOT NULL,`loginInfoId` BIGINT NOT NULL, PRIMARY KEY (`userID`, `loginInfoId`));
create table `passwordinfo` (`hasher` VARCHAR(255) NOT NULL,`password` VARCHAR(255) NOT NULL,`salt` VARCHAR(255),`loginInfoId` BIGINT NOT NULL);
create table `oauth2info` (`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`accesstoken` VARCHAR(255) NOT NULL,`tokentype` VARCHAR(255),`expiresin` INTEGER,`refreshtoken` VARCHAR(255),`logininfoid` BIGINT NOT NULL);



# --- !Downs

drop table `oauth2info`;
drop table `passwordinfo`;
drop table `userlogininfo`;
drop table `logininfo`;
drop table `user`;